### ISSUE TITLE
Wallet goes into "emergency mode" and produces an error message when closing the channel 

### ISSUE THREAD

**Issue by raindogdance** [btcontract/lnwallet#13]
Mobile version. The error text is quoted below (it says "9 more" at the end but it's not "clickable" in my version). I cannot access the wallet version right now, as all I can do is tap on "show error report" or "view mnemonic code".

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lightning.wallet/com.lightning.wallet.LNOpsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'net.sqlcipher.Cursor com.lightning.wallet.lnutils.CipherOpenHelper.select(java.lang.String, scala.collection.Seq)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'net.sqlcipher.Cursor com.lightning.wallet.lnutils.CipherOpenHelper.select(java.lang.String, scala.collection.Seq)' on a null object reference
	at com.lightning.wallet.lnutils.ChannelWrap$.get(StorageWrap.scala:59)
	at com.lightning.wallet.WalletApp$ChannelManager$.<init>(WalletApp.scala:129)
	at com.lightning.wallet.WalletApp.ChannelManager$lzycompute(WalletApp.scala:123)
	at com.lightning.wallet.WalletApp.ChannelManager(WalletApp.scala:123)
	at com.lightning.wallet.LNOpsActivity.INIT(LNOpsActivity.scala:49)
	at com.lightning.wallet.TimerActivity$class.onCreate(Utils.scala:457)
	at com.lightning.wallet.LNOpsActivity.onCreate(LNOpsActivity.scala:19)
	at android.app.Activity.performCreate(Activity.java:6998)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
	... 9 more

that's how the wallet looks like atm, no further options/menus except these two (cannot go anywhere else): https://imgur.com/a/iHEGt

**Comment by raindogdance** [comment]
that's how the wallet looks like atm, no further options/menus except these two (cannot go anywhere else): https://imgur.com/a/iHEGt

**Comment by btcontract** [comment]
This looks very much like a bug which was fixed in the last update, what's your current app version? (can be seen a app menu -> wallet settings).

Also, does this persist after an application is restarted?

**Comment by raindogdance** [comment]
Ah, yes, figured out now how to access the settings again! When I restart the application, I can access the "bitcoin" wallet again, but under "lightning" there is still the "closing a payment channel" screen. 
The version is v0.01-6

**Comment by btcontract** [comment]
v0.01-6 is the latest version, this particular bug should not be happening there but here it is, thanks for reporting! As far as I understand an app works normally after restart which is expected with this bug.

"closing a payment channel" screen is normal behavior, it will go away after an app is restarted with closing transaction having 2 or more confirmations. But you can open a new channel right away. Also, this will be changed soon (working on a big UI update currently).

**Comment by raindogdance** [comment]
> "closing a payment channel" screen is normal behavior, it will go away after an app is restarted with closing transaction having 2 or more confirmations. But you can open a new channel right away. 

When I go to the "lightning" section of the wallet, I only can access the "closing a payment channel" screen (which has been there for around 24h now). I guess the only way to open a new channel is to "force close" the current channel, since it doesn't seem to be closed down regularly?

> (working on a big UI update currently).

Awesome :)

**Comment by btcontract** [comment]
I get it now. On initiating a cooperative closing a channel enters a special "negotiation" state which typically ends within seconds (and UI also would have changed). But if stuck in-flight payments exist then negotiation will persist until they are resolved which may take hundreds of blocks.

And stuck payments currently happen regularly on testnet, I even made a section about them on site: http://lightning-wallet.com/using-lightning-wallet#stuck-payments

Once a stuck payment happens you can either wait until it is failed (and continue using a wallet in the meantime) or force-close a channel and open another one which is perhaps the best option on testnet.

So yes, just proceed with "Force close" and you'll be able to open another channel right away.
